# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:                [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Just.A.Coder
tagline:          'A full-stack JS engineer'
description:      'Oh well!'
url:              https://www.justacoder.in
baseurl:          https://www.justacoder.in

author:
  name:           'Avinash'
  url:            https://github.com/avin45h

paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/avin45h/avin45h.github.io
