# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Just<br/>A<br/>Coder'
tagline:          'Being a coder is awesome'
description:      'Being a coder is awesome'
url:              http://justacoder.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
